server:
  port: 8080

spring:
  application:
    name: oauth2-server
  datasource:
    url: jdbc:mysql://localhost:3306/security?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
